DROP TABLE IF EXISTS Gift_certificate_Tag;
DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS Gift_certificate;

CREATE TABLE Gift_certificate
(
    id               int generated by default as identity primary key,
    name             varchar(100) not null,
    description      varchar,
    price            DECIMAL(6, 2) CHECK ( price > 10 ),
    duration         int CHECK ( duration > 0 ),
    create_date      timestamp,
    last_update_date timestamp
);

CREATE TABLE Tag
(
    id   int generated by default as identity primary key,
    name varchar(100) not null unique
);

CREATE TABLE Gift_certificate_Tag
(
    gift_certificate_id int references Gift_certificate (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    tag_id              int references Tag (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    primary key (gift_certificate_id, tag_id)
);

INSERT INTO Gift_certificate
values (DEFAULT, '100$', 'anything gift card', 131.5, 8, current_timestamp, current_timestamp),
       (DEFAULT, '200$', 'anything gift card', 255.3, 12, current_timestamp, current_timestamp),
       (DEFAULT, '200$', 'only for toys shops card', 255.3, 11, current_timestamp, current_timestamp),
       (DEFAULT, '50$', 'only for toys shops card', 70.37, 14, current_timestamp, current_timestamp),
       (DEFAULT, '200$', 'happy birthday', 230.75, 30, current_timestamp, current_timestamp),
       (DEFAULT, '250$', 'happy birthday', 270.75, 30, current_timestamp, current_timestamp),
       (DEFAULT, '300$', 'happy birthday', 330.75, 30, current_timestamp, current_timestamp),
       (DEFAULT, '350$', 'happy birthday', 370.75, 30, current_timestamp, current_timestamp),
       (DEFAULT, '500$', 'Nike shop only card', 535.25, 12, current_timestamp, current_timestamp),
       (DEFAULT, '500$', 'car shops only card', 535.25, 12, current_timestamp, current_timestamp),
       (DEFAULT, '700$', 'car shops only card', 775.25, 25, current_timestamp, current_timestamp),
       (DEFAULT, '500$', 'happy wedding day', 595.25, 32, current_timestamp, current_timestamp),
       (DEFAULT, '700$', 'happy wedding day', 785.25, 32, current_timestamp, current_timestamp),
       (DEFAULT, '1000$', 'happy wedding day', 1145.25, 32, current_timestamp, current_timestamp);

INSERT INTO Tag
values (DEFAULT, 'wedding'),
       (DEFAULT, 'birthday'),
       (DEFAULT, 'health'),
       (DEFAULT, 'auto-moto'),
       (DEFAULT, 'anything'),
       (DEFAULT, 'sports'),
       (DEFAULT, 'toys');

INSERT INTO gift_certificate_tag
values (1, 5),
       (2, 5),
       (3, 7),
       (4, 7),
       (5, 2),
       (6, 2),
       (7, 2),
       (8, 2),
       (9, 6),
       (10, 4),
       (11, 4),
       (12, 1),
       (13, 1),
       (14, 1);