server:
  port: 8080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
        user-registration:
          username: server
          password: 123456
  data:
    web:
      pageable:
        page-parameter: offset
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/module4
    username: postgres
    password: postgres
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      data-source-properties:
        prepStmtCacheEnabled: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true