server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/module3
    username: postgres
    password: postgres
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      data-source-properties:
        prepStmtCacheEnabled: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true