CREATE TABLE Gift_certificate
(
    id               int generated by default as identity primary key,
    name             varchar(100) not null,
    description      varchar,
    price            DECIMAL(8, 2) CHECK ( price > 10 ),
    duration         int CHECK ( duration > 0 ),
    create_date      timestamp,
    last_update_date timestamp
);

CREATE TABLE Tag
(
    id   int generated by default as identity primary key,
    name varchar(100) not null unique
);

CREATE TABLE Gift_certificate_Tag
(
    gift_certificate_id int references Gift_certificate (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    tag_id              int references Tag (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    primary key (gift_certificate_id, tag_id)
);

CREATE TABLE Users
(
    id        int generated by default as identity primary key,
    name      varchar(100) not null,
    last_name varchar(100) not null,
    email     varchar(320) not null unique
);

CREATE TABLE Orders
(
    id          int generated by default as identity primary key,
    cost        DECIMAL(10, 2) CHECK ( cost > 0 ),
    create_date timestamp,
    user_id     int references Users (id)
);

CREATE TABLE orders_gift_certificate
(
    orders_id           int references Orders (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    gift_certificate_id int references Gift_certificate (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    primary key (orders_id, gift_certificate_id),
    count               int
);