DROP TABLE IF EXISTS Gift_certificate_Tag;
DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS Gift_certificate;

CREATE TABLE Gift_certificate
(
    id               int generated by default as identity primary key,
    name             varchar(100) not null,
    description      varchar,
    price            DECIMAL(6, 2) CHECK ( price > 10 ),
    duration         int CHECK ( duration > 0 ),
    create_date      timestamp,
    last_update_date timestamp
);

CREATE TABLE Tag
(
    id   int generated by default as identity primary key,
    name varchar(100) not null unique
);

CREATE TABLE Gift_certificate_Tag
(
    gift_certificate_id int references Gift_certificate (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    tag_id              int references Tag (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    primary key (gift_certificate_id, tag_id)
);